#!/bin/sh
# File generated by ocamlbuild

cd /home/osboxes/Downloads/Projects/OcamlCompiler

rm -f pi.cmi
rm -f pi.cmo
# Also clean the script itself
rm -f /home/osboxes/Downloads/Projects/OcamlCompiler/_build/sanitize.sh
